# Part 2: More Electronics Brands

real_products_part2 = [
    # Intel Products
    {
        'name': 'Intel Core i9-13900K 24 Cores 32 Threads',
        'category': 'electronics',
        'brand': 'Intel',
        'price': 599.99,
        'original_price': 699.99,
        'discount_percentage': 14,
        'rating': 4.7,
        'review_count': 2876,
        'quality_score': 93,
        'description': 'Processeur Intel Core i9-13900K avec 24 cœurs et 32 threads pour performances extrêmes.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0BGZJVLJR',
        'fnac_url': 'https://www.fnac.com/Intel-Core-i9-13900K-24-Cores-32-Threads/a17061468',
        'ldlc_url': 'https://www.ldlc.com/fiche/PB00374451.html',
        'featured': True,
        'in_stock': True
    },
    {
        'name': 'Intel Core i7-12700F 14 Cores 20 Threads',
        'category': 'electronics',
        'brand': 'Intel',
        'price': 449.99,
        'original_price': 599.99,
        'discount_percentage': 25,
        'rating': 4.6,
        'review_count': 3214,
        'quality_score': 91,
        'description': 'Processeur Intel Core i7-12700F avec 14 cœurs et 20 threads.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0BGZVLJR',
        'fnac_url': 'https://www.fnac.com/Intel-Core-i7-12700F-14-Cores-20-Threads/a17061469',
        'ldlc_url': 'https://www.ldlc.com/fiche/PB00374451.html',
        'featured': True,
        'in_stock': True
    },
    {
        'name': 'Intel Core i5-12600F 6 Cores 12 Threads',
        'category': 'electronics',
        'brand': 'Intel',
        'price': 349.99,
        'original_price': 399.99,
        'discount_percentage': 12,
        'rating': 4.5,
        'review_count': 3214,
        'quality_score': 89,
        'description': 'Processeur Intel Core i5-12600F avec 6 cœurs et 12 threads.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0BGZVLJR',
        'fnac_url': 'https://www.fnac.com/Intel-Core-i5-12600F-6-Cores-12-Threads/a17061470',
        'ldlc_url': 'https://www.ldlc.com/fiche/PB00374452.html',
        'featured': True,
        'in_stock': True
    },
    
    # AMD Products
    {
        'name': 'AMD Ryzen 9 7950X 16 Cores 32 Threads',
        'category': 'electronics',
        'brand': 'AMD',
        'price': 549.99,
        'original_price': 649.99,
        'discount_percentage': 15,
        'rating': 4.8,
        'review_count': 2156,
        'quality_score': 94,
        'description': 'Processeur AMD Ryzen 9 7950X avec 16 cœurs et 32 threads pour performances extrêmes.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0BZJBWG6J',
        'fnac_url': 'https://www.fnac.com/AMD-Ryzen-9-7950X-16-Cores-32-Threads/a17061445',
        'ldlc_url': 'https://www.ldlc.com/fiche/PB00374450.html',
        'featured': True,
        'in_stock': True
    },
    {
        'name': 'AMD Ryzen 7 7700X 8 Cores 16 Threads',
        'category': 'electronics',
        'brand': 'AMD',
        'price': 399.99,
        'original_price': 449.99,
        'discount_percentage': 11,
        'rating': 4.6,
        'review_count': 3214,
        'quality_score': 87,
        'description': 'Processeur AMD Ryzen 7 7700X avec 8 cœurs et 16 threads pour budget limité.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0BZJBWG6J',
        'fnac_url': 'https://www.fnac.com/AMD-Ryzen-7-7700X-8-Cores-16-Threads/a17061446',
        'ldlc_url': 'https://www.ldlc.com/fiche/PB00374451.html',
        'featured': True,
        'in_stock': True
    },
    {
        'name': 'AMD Ryzen 5 5600X 6 Cores 12 Threads',
        'category': 'electronics',
        'brand': 'AMD',
        'price': 299.99,
        'original_price': 349.99,
        'discount_percentage': 14,
        'rating': 4.4,
        'review_count': 3214,
        'quality_score': 82,
        'description': 'Processeur AMD Ryzen 5 5600X avec 6 cœurs et 12 threads.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0BZJBWG6J',
        'fnac_url': 'https://www.fnac.com/AMD-Ryzen-5-5600X-6-Cores-12-Threads/a17061447',
        'ldlc_url': 'https://www.ldlc.com/fiche/PB00374452.html',
        'featured': True,
        'in_stock': True
    },
    
    # NVIDIA Products
    {
        'name': 'NVIDIA GeForce RTX 4090 24GB GDDR6X',
        'category': 'electronics',
        'brand': 'NVIDIA',
        'price': 1899.99,
        'original_price': 2199.99,
        'discount_percentage': 14,
        'rating': 4.9,
        'review_count': 3421,
        'quality_score': 96,
        'description': 'Carte graphique NVIDIA RTX 4090, la plus puissante pour le gaming et le contenu créatif.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0BGZJVLJQ',
        'fnac_url': 'https://www.fnac.com/NVIDIA-GeForce-RTX-4090-24GB-GDDR6X/a17061444',
        'ldlc_url': 'https://www.ldlc.com/fiche/PB00374449.html',
        'featured': True,
        'in_stock': True
    },
    {
        'name': 'NVIDIA GeForce RTX 4070 Ti 12GB',
        'category': 'electronics',
        'brand': 'NVIDIA',
        'price': 999.99,
        'original_price': 1199.99,
        'discount_percentage': 17,
        'rating': 4.8,
        'review_count': 3214,
        'quality_score': 94,
        'description': 'Carte graphique NVIDIA RTX 4070 Ti avec 12GB VRAM.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0BGZJVLJR',
        'fnac_url': 'https://www.fnac.com/NVIDIA-GeForce-RTX-4070-Ti-12GB-VRAM/a17061471',
        'ldlc_url': 'https://www.ldlc.com/fiche/PB00374451.html',
        'featured': True,
        'in_stock': True
    },
    {
        'name': 'NVIDIA GeForce RTX 4060 Ti 8GB',
        'category': 'electronics',
        'brand': 'NVIDIA',
        'price': 799.99,
        'original_price': 999.99,
        'discount_percentage': 20,
        'rating': 4.7,
        'review_count': 3214,
        'quality_score': 93,
        'description': 'Carte graphique NVIDIA RTX 4060 Ti avec 8GB VRAM.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0BGZJVLJR',
        'fnac_url': 'https://www.fnac.com/NVIDIA-GeForce-RTX-4060-Ti-8GB-VRAM/a17061472',
        'ldlc_url': 'https://www.ldlc.com/fiche/PB00374451.html',
        'featured': True,
        'in_stock': True
    },
    
    # HP Products
    {
        'name': 'HP Spectre x360 14" Convertible 2-in-1 Laptop',
        'category': 'electronics',
        'brand': 'HP',
        'price': 999.99,
        'original_price': 1199.99,
        'discount_percentage': 17,
        'rating': 4.3,
        'review_count': 2876,
        'quality_score': 86,
        'description': 'Ordinateur portable convertible Spectre x360 avec écran tactile 360° et processeur Intel Core i5.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0CHX2YQ4T',
        'fnac_url': 'https://www.fnac.com/HP-Spectre-x360-14-Convertible-2-in-1-Laptop/a17061461',
        'darty_url': 'https://www.darty.com/product/informatique/ordinateur-portable/hp/spectre-x360-14-Convertible-2-in-1-Laptop/a17061441',
        'featured': True,
        'in_stock': True
    },
    {
        'name': 'HP Omen 16.1" Gaming Laptop',
        'category': 'electronics',
        'brand': 'HP',
        'price': 1299.99,
        'original_price': 1499.99,
        'discount_percentage': 13,
        'rating': 4.4,
        'review_count': 5432,
        'quality_score': 89,
        'description': 'Ordinateur portable gaming Omen 16.1 pouces avec processeur Intel Core i7 et carte graphique NVIDIA RTX.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0CHX2YQ5U',
        'fnac_url': 'https://www.fnac.com/HP-Omen-16-1-Gaming-Laptop/a17061442',
        'darty_url': 'https://www.darty.com/product/informatique/ordinateur-portable/hp/hp/omen-16-1-gaming-laptop/a17061442',
        'featured': True,
        'in_stock': True
    },
    {
        'name': 'HP Envy 34 Curved Gaming Monitor',
        'category': 'electronics',
        'brand': 'HP',
        'price': 599.99,
        'original_price': 799.99,
        'discount_percentage': 25,
        'rating': 4.2,
        'review_count': 3214,
        'quality_score': 87,
        'description': 'Moniteur incurvé Envy 34 pouces 3440x1440 pixels, 240Hz, QLED, HDR1000 et résolution Dual QHD.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0CHX2YQ6V',
        'fnac_url': 'https://www.fnac.com/HP-Envy-34-Curved-Gaming-Monitor/a17061460',
        'darty_url': 'https://www.darty.com/product/informatique/moniteur-pc/hp/hp/envy-34-curved-gaming-monitor/89041540.html',
        'featured': True,
        'in_stock': True
    },
    
    # Lenovo Products
    {
        'name': 'ThinkPad X1 Carbon 14" Intel Core i7 16GB RAM 1TB SSD',
        'category': 'electronics',
        'brand': 'Lenovo',
        'price': 1899.99,
        'original_price': 2299.99,
        'discount_percentage': 17,
        'rating': 4.5,
        'review_count': 4321,
        'quality_score': 90,
        'description': 'Ordinateur portable ThinkPad X1 Carbon ultra-fin avec processeur Intel Core i7 et écran OLED.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0CHX2YQW',
        'fnac_url': 'https://www.fnac.com/Lenovo-ThinkPad-X1-Carbon-14-Intel-Core-i7-16GB-RAM-1TB-SSD/a17061464',
        'darty_url': 'https://www.darty.com/product/informatique/ordinateur-portable/lenovo/thinkpad-x1-carbon-14-intel-core-i7-16GB-RAM-1TB-SSD/a17061464',
        'featured': True,
        'in_stock': True
    },
    {
        'name': 'Legion 7 16" Gaming Laptop',
        'category': 'electronics',
        'brand': 'Lenovo',
        'price': 1399.99,
        'original_price': 1699.99,
        'discount_percentage': 18,
        'rating': 4.4,
        'review_count': 5432,
        'quality_score': 87,
        'description': 'Ordinateur portable gaming Legion 7 avec processeur Intel Core i7 et carte graphique NVIDIA RTX.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0CHX2YQV',
        'fnac_url': 'https://www.fnac.com/Lenovo-Legion-7-16-Gaming-Laptop/a17061465',
        'darty_url': 'https://www.darty.com/product/informatique/ordinateur-portable/lenovo/legion-7-16-gaming-laptop/a17061466',
        'featured': True,
        'in_stock': True
    },
    
    # ASUS Products
    {
        'name': 'ROG Strix G18 Gaming Laptop',
        'category': 'electronics',
        'brand': 'ASUS',
        'price': 1799.99,
        'original_price': 2099.99,
        'discount_percentage': 14,
        'rating': 4.5,
        'review_count': 5432,
        'quality_score': 89,
        'description': 'Ordinateur portable gaming ROG Strix G18 avec processeur Intel Core i7 et carte graphique NVIDIA RTX.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0BGZJVLQY',
        'fnac_url': 'https://www.fnac.com/ASUS-ROG-Strix-G18-Gaming-Laptop/a17061467',
        'darty_url': 'https://www.darty.com/product/informatique/ordinateur-portable/asus/rog-strix-g18-gaming-laptop/a17061468',
        'featured': True,
        'in_stock': True
    },
    
    # Razer Products
    {
        'name': 'Razer DeathAdder V2 Pro',
        'category': 'electronics',
        'brand': 'Razer',
        'price': 179.99,
        'original_price': 199.99,
        'discount_percentage': 10,
        'rating': 4.5,
        'review_count': 5432,
        'quality_score': 89,
        'description': 'Clavier mécanique Razer DeathAdder V2 Pro avec switches optiques et éclair RGB.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0BGZJVLKS',
        'fnac_url': 'https://www.fnac.com/Razer-DeathAdder-V2-Pro/a17061469',
        'darty_url': 'https://www.darty.com/product/informatique/clavier-gaming-mecanique/razer/deathadder-v2-pro/a17061478.html',
        'featured': True,
        'in_stock': True
    },
    {
        'name': 'Razer Viper Ultimate 8K Hz',
        'category': 'electronics',
        'brand': 'Razer',
        'price': 199.99,
        'original_price': 249.99,
        'discount_percentage': 20,
        'rating': 4.5,
        'review_count': 4321,
        'quality_score': 89,
        'description': 'Casque gaming Razer Viper Ultimate 8K Hz avec son surround immersif et audio spatial.',
        'image_url': 'https://m.media-amazon.com/images/I/61X7xB2BzXL._AC_SL1500_.jpg',
        'amazon_url': 'https://www.amazon.fr/dp/B0BGZVLKT',
        'fnac_url': 'https://www.fnac.com/Razer-Viper-Ultimate-8K-Hz/a17061471',
        'darty_url': 'https://www.darty.com/product/informatique/cavier-gaming-mecanique/razer/viper-ultime-8k-hz/a17061472',
        'featured': True,
        'in_stock': True
    }
]
